workflows:
  njabulo-app:
    name: Njabulo Jb App
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: 3.16.0
    scripts:
      - name: Clean and Build
        script: |
          flutter clean
          flutter pub get
          flutter build apk --debug
          cp build/app/outputs/flutter-apk/app-debug.apk Njabulo-Jb.apk
    artifacts:
      - Njabulo-Jb.apk
