workflows:
  njabulo-app:
    name: Njabulo Jb App
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: 3.22.0
      xcode: latest
    scripts:
      - name: Delete old lock file
        script: rm -f pubspec.lock
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
          cp build/app/outputs/flutter-apk/app-release.apk Njabulo-Jb.apk
    artifacts:
      - Njabulo-Jb.apk
